<?php
$skoler = array('Fylket Brukerstøtte' => '2',
                'Fylket Systemdrift' => '39',
                'Fylket Infrastruktur' => '40',
                'Vågsbygd' => '3',
                'Vennesla' => '26',
                'Kvadraturen' => '34',
                'Tangen' => '4',
                'KKG' => '33',
                'Søgne' => '66',
                'Mandal' => '37',
                'Byremo' => '27',
                'Farsund' => '28',
                'Lista' => '35',
                'Lyngdal' => '36',
                'Flekkefjord' => '29',
                'Kvinesdal' => '30',
                'Sirdal' => '38'
               );

  $avdelinger = array('Alle' => 'ALLE',
                      'Vennesla' => 'VGS_VEN',
                      'Søgne' => 'VGS_SOG',
                      'Lista' => 'VGS_EVG_LIS',
                      'Farsund' => 'VGS_EVG_FAR',
                      'Lyngdal' => 'VGS_EVG_LYN',
                      'Eilert' => 'VGS_EVG',
                      'Byremo' => 'VGS_BYR',
                      'Sirdal' => 'VGS_SIR',
                      'Mandal' => 'VGS_MAN',
                      'Alle fylket' => 'FRS_ALLE',
                      'Fylket Service' => 'FRS_IT',
                      'Fylket Infrastruktur' => 'FRS_Infrastruktur',
                      'Fylket Systemdrift' => 'FRS_Systemdrift',
                      'Kvadraturen' => 'VGS_KVA',
                      'KKG' => 'VGS_KKG',
                      'Tangen' => 'VGS_TAN',
                      'Vågsbygd' => 'VGS_VAG',
                      'Flekkefjord' => 'VGS_FVG_FLE',
                      'Kvinesdal' => 'VGS_FVG_KVI',
                      'FVG' => 'FVG');
